const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('popnative', {
  openDialog: () => ipcRenderer.invoke('dialog:open'),
  saveDialog: (suggested) => ipcRenderer.invoke('dialog:save', suggested),
  readFile: (p) => ipcRenderer.invoke('file:read', p),
  writeFile: (p, text) => ipcRenderer.invoke('file:write', p, text),
  exists: (p) => ipcRenderer.invoke('file:exists', p),
  listDir: (p) => ipcRenderer.invoke('dir:list', p),
  paths: () => ipcRenderer.invoke('app:paths'),
  pathForFile: (file) => webUtils.getPathForFile(file),
  onCommand: (cb) => ipcRenderer.on('cmd', (e, data) => cb(data)),
  dirDialog: (title) => ipcRenderer.invoke('dialog:dir', title),
  closeAck: () => ipcRenderer.invoke('close:ack'),
  closeProceed: () => ipcRenderer.invoke('close:proceed'),
  tfDetect: () => ipcRenderer.invoke('tf:detect'),
  tfFonts: (tfPath) => ipcRenderer.invoke('fonts:tf', tfPath),
  resolveIcons: (names, dirs, tfPath) => ipcRenderer.invoke('icons:resolve', names, dirs, tfPath),
  refreshIcons: () => ipcRenderer.invoke('icons:refresh'),
  listIcons: (dirs, tfPath) => ipcRenderer.invoke('icons:list', dirs, tfPath),
  imageSave: (name, bytes, targetPath) => ipcRenderer.invoke('image:save', name, bytes, targetPath),
  tankPath: (popName, tfPath, starts) => ipcRenderer.invoke('tank:path', popName, tfPath, starts),
  mapData: (popName, tfPath) => ipcRenderer.invoke('map:data', popName, tfPath),
  mapGeo: (popName, tfPath) => ipcRenderer.invoke('map:geo', popName, tfPath),
  mapTexture: (popName, tfPath) => ipcRenderer.invoke('map:texture', popName, tfPath),
  winList: () => ipcRenderer.invoke('wins:list'),
  dockStart: (target, opts) => ipcRenderer.invoke('dock:start', target, opts),
  dockPos: (position) => ipcRenderer.invoke('dock:pos', position),
  dockStop: () => ipcRenderer.invoke('dock:stop'),
  editorGoto: (editor, file, line) => ipcRenderer.invoke('editor:goto', editor, file, line),
  watchAdd: (p) => ipcRenderer.invoke('watch:add', p),
  watchRemove: (p) => ipcRenderer.invoke('watch:remove', p),
  fsxList: (dir) => ipcRenderer.invoke('fsx:list', dir),
  matRead: (rel, tfPath) => ipcRenderer.invoke('mat:read', rel, tfPath),
  matTexture: (rel, tfPath) => ipcRenderer.invoke('mat:texture', rel, tfPath),
  modelLoad: (src, tfPath) => ipcRenderer.invoke('model:load', src, tfPath),
  hlmvFind: (tfPath, override) => ipcRenderer.invoke('hlmv:find', tfPath, override),
  hlmvOpen: (exe, tfPath, mdlPath) => ipcRenderer.invoke('hlmv:open', exe, tfPath, mdlPath),
  potatoList: (rel) => ipcRenderer.invoke('potato:list', rel),
  potatoModel: (rel, tfPath) => ipcRenderer.invoke('potato:model', rel, tfPath),
  potatoMap: (name, tfPath) => ipcRenderer.invoke('potato:map', name, tfPath),
  mapFlush: () => ipcRenderer.invoke('map:flush')
});
