#!/usr/bin/env bash
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SDK="$HERE/sdk"
EMSDK="${EMSDK_ROOT:-/c/Users/jakub/emsdk}"
OUT="$HERE/build"
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 4)}"

if [ ! -d "$SDK/public" ]; then
  echo "Vendored SDK missing at $SDK" >&2
  exit 1
fi

if [ ! -f "$EMSDK/emsdk_env.sh" ]; then
  echo "emscripten not found at $EMSDK; set EMSDK_ROOT" >&2
  exit 1
fi

source "$EMSDK/emsdk_env.sh" >/dev/null 2>&1

PROTOC="$SDK/thirdparty/protobuf-2.6.1/bin/win64/protoc.exe"
PROTO_SOURCES=(
  "$SDK/gcsdk/steammessages.proto"
  "$SDK/game/shared/base_gcmessages.proto"
  "$SDK/game/shared/econ/econ_gcmessages.proto"
  "$SDK/game/shared/tf/tf_gcmessages.proto"
  "$SDK/game/shared/tf/tf_proto_def_messages.proto"
)

INCLUDES=(
  -I"$SDK/public"
  -I"$SDK/public/tier0"
  -I"$SDK/public/tier1"
  -I"$SDK/common"
  -I"$SDK"
  -I"$SDK/game/server"
  -I"$SDK/game/shared"
  -I"$SDK/game/shared/econ"
  -I"$SDK/game/server/NextBot"
  -I"$SDK/gcsdk/steamextra"
  -I"$SDK/game/shared/hl2"
  -I"$SDK/game/server/tf"
  -I"$SDK/game/shared/Multiplayer"
  -I"$SDK/game/shared/tf"
  -I"$OUT/proto"
  -I"$SDK/thirdparty/protobuf-2.6.1/src"
  -I"$HERE/shim/protobuf"
  -I"$HERE/shim"
  -I"$OUT/generated"
)

DEFINES=(
  -DPOSIX -DLINUX -D_LINUX -DGNUC -DNDEBUG -DCOMPILER_GCC -DNO_VCR
  -DGAME_DLL -DVECTOR -DVERSION_SAFE_STEAM_API_INTERFACES
  -DINCLUDED_STEAM2_USERID_STRUCTS -DSWDS -DUSE_NAV_MESH -DREPLAY_ENABLED
  -DUSES_ECON_ITEMS
  -DTF_DLL -DENABLE_GC_MATCHMAKING -DGLOWS_ENABLE -DUSE_DYNAMIC_ASSET_LOADING -DNEXT_BOT
  -DDISABLE_GC_CONNECTION -DDISABLE_IN_SOURCESDK -DINVENTORY_VIA_WEBAPI
)

FLAGS=(
  -std=c++14 -msse2 -msimd128 -fpermissive -w -O2
)

NAV_SOURCES=(
  "$SDK/game/server/nav_area.cpp"
  "$SDK/game/server/nav_mesh.cpp"
  "$SDK/game/server/nav_file.cpp"
  "$SDK/game/server/nav_ladder.cpp"
)

COLLISION_SOURCES=(
  "$HERE/shim/bspcollision.cpp"
  "$HERE/shim/dispcollision.cpp"
  "$HERE/shim/capi.cpp"
  "$HERE/shim/tier0stub.cpp"
  "$SDK/public/builddisp.cpp"
  "$SDK/public/dispcoll_common.cpp"
  "$SDK/public/disp_common.cpp"
  "$SDK/public/disp_powerinfo.cpp"
  "$SDK/public/collisionutils.cpp"
  "$SDK/tier1/generichash.cpp"
  "$SDK/mathlib/mathlib_base.cpp"
  "$SDK/mathlib/vmatrix.cpp"
  "$SDK/mathlib/sseconst.cpp"
  "$SDK/mathlib/powsse.cpp"
)

ENT_SOURCES=(
  "$SDK/game/server/baseentity.cpp"
  "$SDK/game/server/cbase.cpp"
  "$SDK/game/server/entitylist.cpp"
  "$SDK/game/server/logicentities.cpp"
  "$SDK/game/server/logicrelay.cpp"
  "$SDK/game/server/doors.cpp"
  "$SDK/game/server/func_movelinear.cpp"
  "$SDK/game/server/bmodels.cpp"
  "$SDK/game/server/modelentities.cpp"
  "$SDK/game/server/pathtrack.cpp"
  "$SDK/game/server/pathcorner.cpp"
  "$SDK/game/server/trains.cpp"
  "$SDK/game/server/buttons.cpp"
  "$SDK/game/server/EnvSpark.cpp"
  "$SDK/game/server/movement.cpp"
  "$SDK/game/server/soundscape.cpp"
  "$SDK/game/server/soundscape_system.cpp"
  "$SDK/game/server/basetempentity.cpp"
  "$SDK/game/server/te_particlesystem.cpp"
  "$SDK/public/map_utils.cpp"
  "$SDK/game/server/sound.cpp"
  "$SDK/game/server/func_areaportal.cpp"
  "$SDK/game/server/func_areaportalwindow.cpp"
  "$SDK/game/server/func_occluder.cpp"
  "$SDK/game/server/func_lod.cpp"
  "$SDK/game/server/func_dust.cpp"
  "$SDK/game/server/point_spotlight.cpp"
  "$SDK/game/server/spotlightend.cpp"
  "$SDK/game/server/lightglow.cpp"
  "$SDK/game/server/shadowcontrol.cpp"
  "$SDK/game/server/WaterLODControl.cpp"
  "$SDK/game/server/env_tonemap_controller.cpp"
  "$SDK/game/server/sun.cpp"
  "$SDK/game/server/EnvShake.cpp"
  "$SDK/game/server/rope.cpp"
  "$SDK/game/server/particle_system.cpp"
  "$SDK/game/server/logicauto.cpp"
  "$SDK/game/server/env_entity_maker.cpp"
  "$SDK/game/server/maprules.cpp"
  "$SDK/game/server/physconstraint.cpp"
  "$SDK/game/shared/beam_shared.cpp"
  "$SDK/game/server/filters.cpp"
  "$SDK/game/server/triggers.cpp"
  "$SDK/game/server/mapentities.cpp"
  "$SDK/game/server/util.cpp"
  "$SDK/game/server/gameinterface.cpp"
  "$SDK/game/server/ServerNetworkProperty.cpp"
  "$SDK/game/server/physics_main.cpp"
  "$SDK/game/shared/baseentity_shared.cpp"
  "$SDK/game/shared/physics_main_shared.cpp"
  "$SDK/game/shared/entitylist_base.cpp"
  "$SDK/game/shared/collisionproperty.cpp"
  "$SDK/game/shared/predictableid.cpp"
  "$SDK/game/server/sendproxy.cpp"
  "$SDK/game/server/hierarchy.cpp"
  "$SDK/game/server/subs.cpp"
  "$SDK/game/server/damagemodifier.cpp"
  "$SDK/game/server/globalstate.cpp"
  "$SDK/game/server/ndebugoverlay.cpp"
  "$SDK/game/server/AI_Criteria.cpp"
  "$SDK/game/server/world.cpp"
  "$SDK/game/server/recipientfilter.cpp"
  "$SDK/game/server/variant_t.cpp"
  "$SDK/game/shared/saverestore.cpp"
  "$SDK/game/server/EntityParticleTrail.cpp"
  "$SDK/game/server/ai_basenpc.cpp"
  "$SDK/game/server/ai_initutils.cpp"
  "$SDK/game/server/ai_namespaces.cpp"
  "$SDK/game/server/ai_squad.cpp"
  "$SDK/game/server/ai_basenpc_schedule.cpp"
  "$SDK/game/server/ai_basenpc_squad.cpp"
  "$SDK/game/server/ai_default.cpp"
  "$SDK/game/server/ai_navigator.cpp"
  "$SDK/game/server/ai_motor.cpp"
  "$SDK/game/server/ai_activity.cpp"
  "$SDK/game/server/ai_utils.cpp"
  "$SDK/game/server/ai_localnavigator.cpp"
  "$SDK/game/server/ai_moveshoot.cpp"
  "$SDK/game/server/ai_pathfinder.cpp"
  "$SDK/game/server/ai_tacticalservices.cpp"
  "$SDK/game/server/ai_node.cpp"
  "$SDK/game/server/ai_network.cpp"
  "$SDK/game/server/ai_waypoint.cpp"
  "$SDK/game/server/ai_route.cpp"
  "$SDK/game/server/AI_Interest_Target.cpp"
  "$SDK/game/server/ai_link.cpp"
  "$SDK/game/server/ai_movesolver.cpp"
  "$SDK/game/server/ai_baseactor.cpp"
  "$SDK/game/server/ai_condition.cpp"
  "$SDK/game/server/ai_event.cpp"
  "$SDK/game/server/ai_goalentity.cpp"
  "$SDK/game/server/gib.cpp"
  "$SDK/game/server/CRagdollMagnet.cpp"
  "$SDK/game/server/cplane.cpp"
  "$SDK/game/server/game.cpp"
  "$SDK/game/server/serverbenchmark_base.cpp"
  "$SDK/game/server/textstatsmgr.cpp"
  "$SDK/game/server/func_areaportalbase.cpp"
  "$SDK/game/server/player_voice_listener.cpp"
  "$SDK/game/server/toolframework_server.cpp"
  "$SDK/game/shared/usermessages.cpp"
  "$SDK/game/shared/usercmd.cpp"
  "$SDK/tier1/bitbuf.cpp"
  "$SDK/game/server/EventLog.cpp"
  "$SDK/game/server/hltvdirector.cpp"
  "$SDK/game/server/ai_saverestore.cpp"
  "$SDK/game/shared/querycache.cpp"
  "$SDK/game/shared/particlesystemquery.cpp"
  "$SDK/game/server/envmicrophone.cpp"
  "$SDK/mathlib/IceKey.cpp"
  "$SDK/game/server/baseviewmodel.cpp"
  "$SDK/game/shared/baseviewmodel_shared.cpp"
  "$SDK/game/shared/gamerules.cpp"
  "$SDK/game/shared/gamerules_register.cpp"
  "$SDK/game/shared/multiplay_gamerules.cpp"
  "$SDK/game/shared/teamplay_gamerules.cpp"
  "$SDK/game/shared/mp_shareddefs.cpp"
  "$SDK/game/shared/gamevars_shared.cpp"
  "$SDK/game/shared/voice_gamemgr.cpp"
  "$SDK/game/server/globals.cpp"
  "$SDK/game/server/team.cpp"
  "$SDK/game/server/player_resource.cpp"
  "$SDK/game/server/basemultiplayerplayer.cpp"
  "$SDK/game/server/tactical_mission.cpp"
  "$SDK/public/registry.cpp"
  "$SDK/game/server/GameStats_BasicStatsFunctions.cpp"
  "$SDK/game/server/playerlocaldata.cpp"
  "$SDK/game/server/fogcontroller.cpp"
  "$SDK/game/server/ai_playerally.cpp"
  "$SDK/game/shared/Sprite.cpp"
  "$SDK/game/shared/weapon_proficiency.cpp"
  "$SDK/game/server/h_ai.cpp"
  "$SDK/game/shared/weapon_parse.cpp"
  "$SDK/game/shared/soundenvelope.cpp"
  "$SDK/game/server/movehelper_server.cpp"
  "$SDK/game/server/physics_bone_follower.cpp"
  "$SDK/game/server/vehicle_base.cpp"
  "$SDK/game/server/fourwheelvehiclephysics.cpp"
  "$SDK/game/server/physics_impact_damage.cpp"
  "$SDK/game/server/func_break.cpp"
  "$SDK/game/server/EntityFlame.cpp"
  "$SDK/game/server/EntityDissolve.cpp"
  "$SDK/game/server/basecombatweapon.cpp"
  "$SDK/game/shared/studio_shared.cpp"
  "$SDK/tier1/datamanager.cpp"
  "$SDK/game/server/RagdollBoogie.cpp"
  "$SDK/game/shared/precache_register.cpp"
  "$SDK/game/shared/physics_shared.cpp"
  "$SDK/game/shared/physics_saverestore.cpp"
  "$SDK/public/bone_setup.cpp"
  "$SDK/game/server/physobj.cpp"
  "$SDK/game/server/physics_prop_ragdoll.cpp"
  "$SDK/game/server/EntityBlocker.cpp"
  "$SDK/game/shared/vehicle_viewblend_shared.cpp"
  "$SDK/game/server/vehicle_baseserver.cpp"
  "$SDK/public/dt_utlvector_send.cpp"
  "$SDK/public/dt_utlvector_common.cpp"
  "$SDK/public/interpolatortypes.cpp"
  "$SDK/game/shared/sceneentity_shared.cpp"
  "$SDK/game/server/ai_basehumanoid.cpp"
  "$SDK/tier1/utlbufferutil.cpp"
  "$SDK/game/server/sceneentity.cpp"
  "$SDK/game/shared/choreoactor.cpp"
  "$SDK/game/shared/choreoevent.cpp"
  "$SDK/game/shared/choreoscene.cpp"
  "$SDK/game/shared/choreochannel.cpp"
  "$SDK/game/server/ai_planesolver.cpp"
  "$SDK/game/shared/interval.cpp"
  "$SDK/game/server/ai_speech.cpp"
  "$SDK/game/server/ai_squadslot.cpp"
  "$SDK/game/server/BaseFlex.cpp"
  "$SDK/game/shared/basecombatcharacter_shared.cpp"
  "$SDK/game/server/ai_dynamiclink.cpp"
  "$SDK/game/server/ai_schedule.cpp"
  "$SDK/game/shared/simtimer.cpp"
  "$SDK/game/shared/ragdoll_shared.cpp"
  "$SDK/tier1/checksum_crc.cpp"
  "$SDK/game/server/ai_task.cpp"
  "$SDK/game/server/props.cpp"
  "$SDK/game/shared/props_shared.cpp"
  "$SDK/game/shared/basecombatweapon_shared.cpp"
  "$SDK/game/server/ai_behavior_assault.cpp"
  "$SDK/game/server/BaseAnimatingOverlay.cpp"
  "$SDK/game/server/ai_moveprobe.cpp"
  "$SDK/game/server/ai_basenpc_movement.cpp"
  "$SDK/game/server/ai_senses.cpp"
  "$SDK/game/server/soundent.cpp"
  "$SDK/game/server/ai_networkmanager.cpp"
  "$SDK/game/server/ragdoll_manager.cpp"
  "$SDK/game/server/ai_memory.cpp"
  "$SDK/game/server/ai_hull.cpp"
  "$SDK/game/server/basecombatcharacter.cpp"
  "$SDK/game/server/baseanimating.cpp"
  "$SDK/game/server/scripted.cpp"
  "$SDK/game/server/ai_hint.cpp"
  "$SDK/game/server/point_template.cpp"
  "$SDK/game/server/TemplateEntities.cpp"
  "$SDK/game/server/lights.cpp"
  "$SDK/game/server/ai_behavior.cpp"
  "$SDK/game/server/ai_behavior_lead.cpp"
  "$SDK/game/shared/mapentities_shared.cpp"
  "$SDK/game/shared/movevars_shared.cpp"
  "$SDK/game/shared/EntityParticleTrail_Shared.cpp"
  "$SDK/game/server/player.cpp"
  "$SDK/game/shared/baseplayer_shared.cpp"
  "$SDK/game/shared/baseparticleentity.cpp"
  "$SDK/game/shared/ammodef.cpp"
  "$SDK/game/shared/activitylist.cpp"
  "$SDK/game/shared/eventlist.cpp"
  "$SDK/game/shared/GameStats.cpp"
  "$SDK/game/server/EffectsServer.cpp"
  "$SDK/game/server/gametrace_dll.cpp"
  "$SDK/game/server/saverestore_gamedll.cpp"
  "$SDK/game/shared/decals.cpp"
  "$SDK/game/server/timedeventmgr.cpp"
  "$SDK/public/stringregistry.cpp"
  "$SDK/tier1/mempool.cpp"
  "$SDK/tier1/tier1.cpp"
  "$SDK/tier1/interface.cpp"
  "$SDK/game/shared/SoundEmitterSystem.cpp"
  "$HERE/shim/randomstub.cpp"
  "$SDK/game/shared/igamesystem.cpp"
  "$SDK/game/shared/util_shared.cpp"
  "$SDK/game/shared/animation.cpp"
  "$SDK/game/shared/ModelSoundsCache.cpp"
  "$SDK/public/studio.cpp"
  "$SDK/tier1/utlstring.cpp"
  "$SDK/tier1/stringpool.cpp"
  "$SDK/tier1/strtools_unicode.cpp"
  "$SDK/tier1/KeyValues.cpp"
  "$SDK/game/shared/takedamageinfo.cpp"
  "$SDK/game/shared/debugoverlay_shared.cpp"
  "$SDK/game/shared/gamestringpool.cpp"
  "$SDK/tier1/convar.cpp"
  "$SDK/tier1/generichash.cpp"
  "$SDK/tier1/strtools.cpp"
  "$SDK/tier1/utlbuffer.cpp"
  "$SDK/tier1/utlsymbol.cpp"
  "$SDK/tier1/characterset.cpp"
  "$SDK/public/dt_send.cpp"
  "$SDK/public/collisionutils.cpp"
  "$SDK/mathlib/mathlib_base.cpp"
  "$SDK/mathlib/vmatrix.cpp"
  "$SDK/mathlib/sseconst.cpp"
  "$SDK/mathlib/powsse.cpp"
  "$SDK/mathlib/color_conversion.cpp"
  "$SDK/tier1/checksum_md5.cpp"
  "$SDK/game/server/SkyCamera.cpp"
  "$HERE/shim/tier0stub.cpp"
  "$HERE/shim/enginestub.cpp"
  "$HERE/shim/keyvaluesstub.cpp"
  "$HERE/shim/ssemath_wasm.cpp"
  "$HERE/shim/engineimpl.cpp"
  "$HERE/shim/enginedefaults.cpp"
  "$HERE/shim/stringtables.cpp"
  "$HERE/shim/enginetrace.cpp"
  "$HERE/shim/objectpairhash.cpp"
  "$HERE/shim/cvarimpl.cpp"
  "$HERE/shim/filesysimpl.cpp"
  "$HERE/shim/bspcollision.cpp"
  "$HERE/shim/dispcollision.cpp"
  "$SDK/public/builddisp.cpp"
  "$SDK/public/dispcoll_common.cpp"
  "$SDK/public/disp_common.cpp"
  "$SDK/public/disp_powerinfo.cpp"
  "$HERE/shim/entsapi.cpp"
  "$SDK/common/language.cpp"
  "$SDK/common/protoutils.cpp"
  "$SDK/common/randoverride.cpp"
  "$SDK/common/steamid.cpp"
  "$SDK/game/server/AI_ResponseSystem.cpp"
  "$SDK/game/server/CommentarySystem.cpp"
  "$SDK/game/server/EnvBeam.cpp"
  "$SDK/game/server/EnvFade.cpp"
  "$SDK/game/server/EnvHudHint.cpp"
  "$SDK/game/server/EnvLaser.cpp"
  "$SDK/game/server/EnvMessage.cpp"
  "$SDK/game/server/MaterialModifyControl.cpp"
  "$SDK/game/server/NextBot/NavMeshEntities/func_nav_prerequisite.cpp"
  "$SDK/game/server/NextBot/NextBot.cpp"
  "$SDK/game/server/NextBot/NextBotBodyInterface.cpp"
  "$SDK/game/server/NextBot/NextBotComponentInterface.cpp"
  "$SDK/game/server/NextBot/NextBotGroundLocomotion.cpp"
  "$SDK/game/server/NextBot/NextBotIntentionInterface.cpp"
  "$SDK/game/server/NextBot/NextBotInterface.cpp"
  "$SDK/game/server/NextBot/NextBotLocomotionInterface.cpp"
  "$SDK/game/server/NextBot/NextBotManager.cpp"
  "$SDK/game/server/NextBot/NextBotVisionInterface.cpp"
  "$SDK/game/server/NextBot/Path/NextBotChasePath.cpp"
  "$SDK/game/server/NextBot/Path/NextBotPath.cpp"
  "$SDK/game/server/NextBot/Path/NextBotPathFollow.cpp"
  "$SDK/game/server/NextBot/Player/NextBotPlayer.cpp"
  "$SDK/game/server/NextBot/Player/NextBotPlayerBody.cpp"
  "$SDK/game/server/NextBot/Player/NextBotPlayerLocomotion.cpp"
  "$SDK/game/server/NextBot/simple_bot.cpp"
  "$SDK/game/server/PointAngularVelocitySensor.cpp"
  "$SDK/game/server/ai_basenpc_flyer.cpp"
  "$SDK/game/server/ai_basenpc_flyer_new.cpp"
  "$SDK/game/server/ai_basenpc_physicsflyer.cpp"
  "$SDK/game/server/ai_behavior_fear.cpp"
  "$SDK/game/server/ai_behavior_follow.cpp"
  "$SDK/game/server/ai_behavior_rappel.cpp"
  "$SDK/game/server/ai_behavior_standoff.cpp"
  "$SDK/game/server/ai_blended_movement.cpp"
  "$SDK/game/server/ai_concommands.cpp"
  "$SDK/game/server/ai_looktarget.cpp"
  "$SDK/game/server/ai_relationship.cpp"
  "$SDK/game/server/ai_scriptconditions.cpp"
  "$SDK/game/server/ai_sentence.cpp"
  "$SDK/game/server/ai_speechfilter.cpp"
  "$SDK/game/server/ai_trackpather.cpp"
  "$SDK/game/server/base_transmit_proxy.cpp"
  "$SDK/game/server/basegrenade_concussion.cpp"
  "$SDK/game/server/basegrenade_contact.cpp"
  "$SDK/game/server/basegrenade_timed.cpp"
  "$SDK/game/server/bitstring.cpp"
  "$SDK/game/server/client.cpp"
  "$SDK/game/server/colorcorrection.cpp"
  "$SDK/game/server/colorcorrectionvolume.cpp"
  "$SDK/game/server/controlentities.cpp"
  "$SDK/game/server/dynamiclight.cpp"
  "$SDK/game/server/effects.cpp"
  "$SDK/game/server/entity_tools_server.cpp"
  "$SDK/game/server/env_debughistory.cpp"
  "$SDK/game/server/env_effectsscript.cpp"
  "$SDK/game/server/env_particlescript.cpp"
  "$SDK/game/server/env_player_surface_trigger.cpp"
  "$SDK/game/server/env_projectedtexture.cpp"
  "$SDK/game/server/env_screenoverlay.cpp"
  "$SDK/game/server/env_texturetoggle.cpp"
  "$SDK/game/server/env_zoom.cpp"
  "$SDK/game/server/event_tempentity_tester.cpp"
  "$SDK/game/server/explode.cpp"
  "$SDK/game/server/fire.cpp"
  "$SDK/game/server/fire_smoke.cpp"
  "$SDK/game/server/fish.cpp"
  "$SDK/game/server/func_breakablesurf.cpp"
  "$SDK/game/server/func_ladder_endpoint.cpp"
  "$SDK/game/server/func_reflective_glass.cpp"
  "$SDK/game/server/func_smokevolume.cpp"
  "$SDK/game/server/game_ui.cpp"
  "$SDK/game/server/gamedll_replay.cpp"
  "$SDK/game/server/gamehandle.cpp"
  "$SDK/game/server/gameweaponmanager.cpp"
  "$SDK/game/server/genericactor.cpp"
  "$SDK/game/server/genericmonster.cpp"
  "$SDK/game/server/grenadethrown.cpp"
  "$SDK/game/server/guntarget.cpp"
  "$SDK/game/server/h_export.cpp"
  "$SDK/game/server/hl2/Func_Monitor.cpp"
  "$SDK/game/server/hl2/te_gaussexplosion.cpp"
  "$SDK/game/server/info_camera_link.cpp"
  "$SDK/game/server/info_overlay_accessor.cpp"
  "$SDK/game/server/init_factory.cpp"
  "$SDK/game/server/intermission.cpp"
  "$SDK/game/server/item_world.cpp"
  "$SDK/game/server/logic_eventlistener.cpp"
  "$SDK/game/server/logic_measure_movement.cpp"
  "$SDK/game/server/logic_navigation.cpp"
  "$SDK/game/server/message_entity.cpp"
  "$SDK/game/server/monstermaker.cpp"
  "$SDK/game/server/movie_explosion.cpp"
  "$SDK/game/server/nav_area.cpp"
  "$SDK/game/server/nav_colors.cpp"
  "$SDK/game/server/nav_edit.cpp"
  "$SDK/game/server/nav_entities.cpp"
  "$SDK/game/server/nav_file.cpp"
  "$SDK/game/server/nav_generate.cpp"
  "$SDK/game/server/nav_ladder.cpp"
  "$SDK/game/server/nav_merge.cpp"
  "$SDK/game/server/nav_mesh.cpp"
  "$SDK/game/server/nav_mesh_factory.cpp"
  "$SDK/game/server/nav_node.cpp"
  "$SDK/game/server/nav_simplify.cpp"
  "$SDK/game/server/netpropmanager.cpp"
  "$SDK/game/server/npc_vehicledriver.cpp"
  "$SDK/game/server/particle_fire.cpp"
  "$SDK/game/server/particle_light.cpp"
  "$SDK/game/server/particle_smokegrenade.cpp"
  "$SDK/game/server/phys_controller.cpp"
  "$SDK/game/server/physics.cpp"
  "$SDK/game/server/physics_cannister.cpp"
  "$SDK/game/server/physics_fx.cpp"
  "$SDK/game/server/physics_npc_solver.cpp"
  "$SDK/game/server/plasma.cpp"
  "$SDK/game/server/player_command.cpp"
  "$SDK/game/server/player_lagcompensation.cpp"
  "$SDK/game/server/player_pickup.cpp"
  "$SDK/game/server/playerinfomanager.cpp"
  "$SDK/game/server/plugin_check.cpp"
  "$SDK/game/server/point_camera.cpp"
  "$SDK/game/server/point_devshot_camera.cpp"
  "$SDK/game/server/point_playermoveconstraint.cpp"
  "$SDK/game/server/point_worldtext.cpp"
  "$SDK/game/server/pointanglesensor.cpp"
  "$SDK/game/server/pointhurt.cpp"
  "$SDK/game/server/pointteleport.cpp"
  "$SDK/game/server/scratchpad_gamedll_helpers.cpp"
  "$SDK/game/server/scriptedtarget.cpp"
  "$SDK/game/server/skyboxswapper.cpp"
  "$SDK/game/server/slideshow_display.cpp"
  "$SDK/game/server/smoke_trail.cpp"
  "$SDK/game/server/smokestack.cpp"
  "$SDK/game/server/sprite_perfmonitor.cpp"
  "$SDK/game/server/stdafx.cpp"
  "$SDK/game/server/steamjet.cpp"
  "$SDK/game/server/tanktrain.cpp"
  "$SDK/game/server/te.cpp"
  "$SDK/game/server/te_armorricochet.cpp"
  "$SDK/game/server/te_basebeam.cpp"
  "$SDK/game/server/te_beamentpoint.cpp"
  "$SDK/game/server/te_beaments.cpp"
  "$SDK/game/server/te_beamfollow.cpp"
  "$SDK/game/server/te_beamlaser.cpp"
  "$SDK/game/server/te_beampoints.cpp"
  "$SDK/game/server/te_beamring.cpp"
  "$SDK/game/server/te_beamringpoint.cpp"
  "$SDK/game/server/te_beamspline.cpp"
  "$SDK/game/server/te_bloodsprite.cpp"
  "$SDK/game/server/te_bloodstream.cpp"
  "$SDK/game/server/te_breakmodel.cpp"
  "$SDK/game/server/te_bspdecal.cpp"
  "$SDK/game/server/te_bubbles.cpp"
  "$SDK/game/server/te_bubbletrail.cpp"
  "$SDK/game/server/te_clientprojectile.cpp"
  "$SDK/game/server/te_decal.cpp"
  "$SDK/game/server/te_dynamiclight.cpp"
  "$SDK/game/server/te_effect_dispatch.cpp"
  "$SDK/game/server/te_energysplash.cpp"
  "$SDK/game/server/te_explosion.cpp"
  "$SDK/game/server/te_fizz.cpp"
  "$SDK/game/server/te_footprintdecal.cpp"
  "$SDK/game/server/te_glassshatter.cpp"
  "$SDK/game/server/te_glowsprite.cpp"
  "$SDK/game/server/te_impact.cpp"
  "$SDK/game/server/te_killplayerattachments.cpp"
  "$SDK/game/server/te_largefunnel.cpp"
  "$SDK/game/server/te_muzzleflash.cpp"
  "$SDK/game/server/te_physicsprop.cpp"
  "$SDK/game/server/te_playerdecal.cpp"
  "$SDK/game/server/te_projecteddecal.cpp"
  "$SDK/game/server/te_showline.cpp"
  "$SDK/game/server/te_smoke.cpp"
  "$SDK/game/server/te_sparks.cpp"
  "$SDK/game/server/te_sprite.cpp"
  "$SDK/game/server/te_spritespray.cpp"
  "$SDK/game/server/te_worlddecal.cpp"
  "$SDK/game/server/team_control_point.cpp"
  "$SDK/game/server/team_control_point_master.cpp"
  "$SDK/game/server/team_control_point_round.cpp"
  "$SDK/game/server/team_objectiveresource.cpp"
  "$SDK/game/server/team_train_watcher.cpp"
  "$SDK/game/server/tempmonster.cpp"
  "$SDK/game/server/tesla.cpp"
  "$SDK/game/server/test_proxytoggle.cpp"
  "$SDK/game/server/test_stressentities.cpp"
  "$SDK/game/server/testfunctions.cpp"
  "$SDK/game/server/testtraceline.cpp"
  "$SDK/game/server/tf/bot/behavior/demoman/tf_bot_prepare_stickybomb_trap.cpp"
  "$SDK/game/server/tf/bot/behavior/demoman/tf_bot_stickybomb_sentrygun.cpp"
  "$SDK/game/server/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_build_sentry.cpp"
  "$SDK/game/server/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_build_teleporter.cpp"
  "$SDK/game/server/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_idle.cpp"
  "$SDK/game/server/tf/bot/behavior/engineer/mvm_engineer/tf_bot_mvm_engineer_teleport_spawn.cpp"
  "$SDK/game/server/tf/bot/behavior/engineer/tf_bot_engineer_build.cpp"
  "$SDK/game/server/tf/bot/behavior/engineer/tf_bot_engineer_build_dispenser.cpp"
  "$SDK/game/server/tf/bot/behavior/engineer/tf_bot_engineer_build_sentrygun.cpp"
  "$SDK/game/server/tf/bot/behavior/engineer/tf_bot_engineer_build_teleport_entrance.cpp"
  "$SDK/game/server/tf/bot/behavior/engineer/tf_bot_engineer_build_teleport_exit.cpp"
  "$SDK/game/server/tf/bot/behavior/engineer/tf_bot_engineer_building.cpp"
  "$SDK/game/server/tf/bot/behavior/engineer/tf_bot_engineer_move_to_build.cpp"
  "$SDK/game/server/tf/bot/behavior/medic/tf_bot_medic_heal.cpp"
  "$SDK/game/server/tf/bot/behavior/medic/tf_bot_medic_retreat.cpp"
  "$SDK/game/server/tf/bot/behavior/missions/tf_bot_mission_destroy_sentries.cpp"
  "$SDK/game/server/tf/bot/behavior/missions/tf_bot_mission_reprogrammed.cpp"
  "$SDK/game/server/tf/bot/behavior/missions/tf_bot_mission_suicide_bomber.cpp"
  "$SDK/game/server/tf/bot/behavior/nav_entities/tf_bot_nav_ent_destroy_entity.cpp"
  "$SDK/game/server/tf/bot/behavior/nav_entities/tf_bot_nav_ent_move_to.cpp"
  "$SDK/game/server/tf/bot/behavior/nav_entities/tf_bot_nav_ent_wait.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/capture_point/tf_bot_capture_point.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/capture_point/tf_bot_defend_point.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/capture_point/tf_bot_defend_point_block_capture.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/capture_the_flag/tf_bot_attack_flag_defenders.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/capture_the_flag/tf_bot_deliver_flag.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/capture_the_flag/tf_bot_escort_flag_carrier.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/capture_the_flag/tf_bot_fetch_flag.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/creep_wave/tf_bot_creep_wave.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/payload/tf_bot_payload_block.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/payload/tf_bot_payload_guard.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/payload/tf_bot_payload_push.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/raid/tf_bot_companion.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/raid/tf_bot_guard_area.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/raid/tf_bot_mob_rush.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/raid/tf_bot_squad_attack.cpp"
  "$SDK/game/server/tf/bot/behavior/scenario/raid/tf_bot_wander.cpp"
  "$SDK/game/server/tf/bot/behavior/sniper/tf_bot_sniper_attack.cpp"
  "$SDK/game/server/tf/bot/behavior/sniper/tf_bot_sniper_lurk.cpp"
  "$SDK/game/server/tf/bot/behavior/spy/tf_bot_spy_attack.cpp"
  "$SDK/game/server/tf/bot/behavior/spy/tf_bot_spy_backstab.cpp"
  "$SDK/game/server/tf/bot/behavior/spy/tf_bot_spy_escape.cpp"
  "$SDK/game/server/tf/bot/behavior/spy/tf_bot_spy_hide.cpp"
  "$SDK/game/server/tf/bot/behavior/spy/tf_bot_spy_infiltrate.cpp"
  "$SDK/game/server/tf/bot/behavior/spy/tf_bot_spy_leave_spawn_room.cpp"
  "$SDK/game/server/tf/bot/behavior/spy/tf_bot_spy_lurk.cpp"
  "$SDK/game/server/tf/bot/behavior/spy/tf_bot_spy_sap.cpp"
  "$SDK/game/server/tf/bot/behavior/squad/tf_bot_escort_squad_leader.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_approach_object.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_attack.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_behavior.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_dead.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_destroy_enemy_sentry.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_escort.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_get_ammo.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_get_health.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_melee_attack.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_move_to_vantage_point.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_mvm_deploy_bomb.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_retreat_to_cover.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_scenario_monitor.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_seek_and_destroy.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_tactical_monitor.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_taunt.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_use_item.cpp"
  "$SDK/game/server/tf/bot/behavior/tf_bot_use_teleporter.cpp"
  "$SDK/game/server/tf/bot/behavior/training/tf_bot_training.cpp"
  "$SDK/game/server/tf/bot/map_entities/tf_bot_generator.cpp"
  "$SDK/game/server/tf/bot/map_entities/tf_bot_hint.cpp"
  "$SDK/game/server/tf/bot/map_entities/tf_bot_hint_engineer_nest.cpp"
  "$SDK/game/server/tf/bot/map_entities/tf_bot_hint_entity.cpp"
  "$SDK/game/server/tf/bot/map_entities/tf_bot_hint_sentrygun.cpp"
  "$SDK/game/server/tf/bot/map_entities/tf_bot_hint_teleporter_exit.cpp"
  "$SDK/game/server/tf/bot/map_entities/tf_bot_proxy.cpp"
  "$SDK/game/server/tf/bot/map_entities/tf_bot_roster.cpp"
  "$SDK/game/server/tf/bot/map_entities/tf_spawner.cpp"
  "$SDK/game/server/tf/bot/map_entities/tf_spawner_boss.cpp"
  "$SDK/game/server/tf/bot/tf_bot.cpp"
  "$SDK/game/server/tf/bot/tf_bot_body.cpp"
  "$SDK/game/server/tf/bot/tf_bot_locomotion.cpp"
  "$SDK/game/server/tf/bot/tf_bot_manager.cpp"
  "$SDK/game/server/tf/bot/tf_bot_squad.cpp"
  "$SDK/game/server/tf/bot/tf_bot_vision.cpp"
  "$SDK/game/server/tf/bot_npc/bot_npc.cpp"
  "$SDK/game/server/tf/bot_npc/bot_npc_archer.cpp"
  "$SDK/game/server/tf/bot_npc/bot_npc_body.cpp"
  "$SDK/game/server/tf/bot_npc/bot_npc_decoy.cpp"
  "$SDK/game/server/tf/bot_npc/bot_npc_mini.cpp"
  "$SDK/game/server/tf/bot_npc/bot_npc_minion.cpp"
  "$SDK/game/server/tf/entity_ammopack.cpp"
  "$SDK/game/server/tf/entity_armor.cpp"
  "$SDK/game/server/tf/entity_bird.cpp"
  "$SDK/game/server/tf/entity_currencypack.cpp"
  "$SDK/game/server/tf/entity_forcerespawn.cpp"
  "$SDK/game/server/tf/entity_game_text_tf.cpp"
  "$SDK/game/server/tf/entity_healthkit.cpp"
  "$SDK/game/server/tf/entity_intermission.cpp"
  "$SDK/game/server/tf/entity_passtime_ball_spawn.cpp"
  "$SDK/game/server/tf/entity_roundwin.cpp"
  "$SDK/game/server/tf/entity_rune.cpp"
  "$SDK/game/server/tf/entity_soldier_statue.cpp"
  "$SDK/game/server/tf/entity_tfstart.cpp"
  "$SDK/game/server/tf/entity_training_annotations.cpp"
  "$SDK/game/server/tf/func_achievement.cpp"
  "$SDK/game/server/tf/func_capture_zone.cpp"
  "$SDK/game/server/tf/func_changeclass.cpp"
  "$SDK/game/server/tf/func_croc.cpp"
  "$SDK/game/server/tf/func_flag_alert.cpp"
  "$SDK/game/server/tf/func_forcefield.cpp"
  "$SDK/game/server/tf/func_no_build.cpp"
  "$SDK/game/server/tf/func_nogrenades.cpp"
  "$SDK/game/server/tf/func_passtime_goal.cpp"
  "$SDK/game/server/tf/func_passtime_goalie_zone.cpp"
  "$SDK/game/server/tf/func_passtime_no_ball_zone.cpp"
  "$SDK/game/server/tf/func_powerupvolume.cpp"
  "$SDK/game/server/tf/func_regenerate.cpp"
  "$SDK/game/server/tf/func_respawnflag.cpp"
  "$SDK/game/server/tf/func_respawnroom.cpp"
  "$SDK/game/server/tf/func_suggested_build.cpp"
  "$SDK/game/server/tf/halloween/eyeball_boss/eyeball_behavior/eyeball_boss_approach_target.cpp"
  "$SDK/game/server/tf/halloween/eyeball_boss/eyeball_behavior/eyeball_boss_behavior.cpp"
  "$SDK/game/server/tf/halloween/eyeball_boss/eyeball_behavior/eyeball_boss_emerge.cpp"
  "$SDK/game/server/tf/halloween/eyeball_boss/eyeball_behavior/eyeball_boss_emote.cpp"
  "$SDK/game/server/tf/halloween/eyeball_boss/eyeball_behavior/eyeball_boss_idle.cpp"
  "$SDK/game/server/tf/halloween/eyeball_boss/eyeball_behavior/eyeball_boss_launch_rockets.cpp"
  "$SDK/game/server/tf/halloween/eyeball_boss/eyeball_behavior/eyeball_boss_notice.cpp"
  "$SDK/game/server/tf/halloween/eyeball_boss/eyeball_behavior/eyeball_boss_stunned.cpp"
  "$SDK/game/server/tf/halloween/eyeball_boss/eyeball_behavior/eyeball_boss_teleport.cpp"
  "$SDK/game/server/tf/halloween/eyeball_boss/eyeball_boss.cpp"
  "$SDK/game/server/tf/halloween/ghost/ghost.cpp"
  "$SDK/game/server/tf/halloween/halloween_base_boss.cpp"
  "$SDK/game/server/tf/halloween/halloween_behavior/headless_hatman_attack.cpp"
  "$SDK/game/server/tf/halloween/halloween_behavior/headless_hatman_dying.cpp"
  "$SDK/game/server/tf/halloween/halloween_behavior/headless_hatman_emerge.cpp"
  "$SDK/game/server/tf/halloween/halloween_behavior/headless_hatman_terrify.cpp"
  "$SDK/game/server/tf/halloween/halloween_gift_spawn_locations.cpp"
  "$SDK/game/server/tf/halloween/headless_hatman.cpp"
  "$SDK/game/server/tf/halloween/headless_hatman_body.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_behavior/merasmus_aoe_attack.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_behavior/merasmus_attack.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_behavior/merasmus_disguise.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_behavior/merasmus_dying.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_behavior/merasmus_reveal.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_behavior/merasmus_staff_attack.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_behavior/merasmus_stunned.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_behavior/merasmus_teleport.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_behavior/merasmus_throwing_grenade.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_behavior/merasmus_zap.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_body.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_dancer.cpp"
  "$SDK/game/server/tf/halloween/merasmus/merasmus_trick_or_treat_prop.cpp"
  "$SDK/game/server/tf/halloween/spell/tf_spell_pickup.cpp"
  "$SDK/game/server/tf/halloween/zombie/zombie.cpp"
  "$SDK/game/server/tf/halloween/zombie/zombie_behavior/zombie_attack.cpp"
  "$SDK/game/server/tf/halloween/zombie/zombie_behavior/zombie_spawn.cpp"
  "$SDK/game/server/tf/halloween/zombie/zombie_behavior/zombie_special_attack.cpp"
  "$SDK/game/server/tf/halloween/zombie/zombie_spawner.cpp"
  "$SDK/game/server/tf/minigames/tf_duel.cpp"
  "$SDK/game/server/tf/nav_mesh/tf_nav_area.cpp"
  "$SDK/game/server/tf/nav_mesh/tf_nav_interface.cpp"
  "$SDK/game/server/tf/nav_mesh/tf_nav_mesh.cpp"
  "$SDK/game/server/tf/nav_mesh/tf_nav_mesh_edit.cpp"
  "$SDK/game/server/tf/nav_mesh/tf_path_follower.cpp"
  "$SDK/game/server/tf/passtime_ballcontroller.cpp"
  "$SDK/game/server/tf/passtime_ballcontroller_homing.cpp"
  "$SDK/game/server/tf/passtime_ballcontroller_playerseek.cpp"
  "$SDK/game/server/tf/player_vs_environment/archer_proxy.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/behavior/boss_alpha_behavior.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/behavior/boss_alpha_chase_victim.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/behavior/boss_alpha_get_off_me.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/behavior/boss_alpha_guard_spot.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/behavior/boss_alpha_launch_grenades.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/behavior/boss_alpha_launch_rockets.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/behavior/boss_alpha_lost_victim.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/behavior/boss_alpha_nuke_attack.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/behavior/boss_alpha_stunned.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/behavior/boss_alpha_tactical_monitor.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/behavior/boss_alpha_wait_for_players.cpp"
  "$SDK/game/server/tf/player_vs_environment/boss_alpha/boss_alpha.cpp"
  "$SDK/game/server/tf/player_vs_environment/monster_resource.cpp"
  "$SDK/game/server/tf/player_vs_environment/tf_base_boss.cpp"
  "$SDK/game/server/tf/player_vs_environment/tf_boss_battle_logic.cpp"
  "$SDK/game/server/tf/player_vs_environment/tf_mann_vs_machine_logic.cpp"
  "$SDK/game/server/tf/player_vs_environment/tf_point_weapon_mimic.cpp"
  "$SDK/game/server/tf/player_vs_environment/tf_population_manager.cpp"
  "$SDK/game/server/tf/player_vs_environment/tf_populator_interface.cpp"
  "$SDK/game/server/tf/player_vs_environment/tf_populator_spawners.cpp"
  "$SDK/game/server/tf/player_vs_environment/tf_populators.cpp"
  "$SDK/game/server/tf/player_vs_environment/tf_tank_boss.cpp"
  "$SDK/game/server/tf/player_vs_environment/tf_tank_boss_body.cpp"
  "$SDK/game/server/tf/player_vs_environment/tf_upgrades.cpp"
  "$SDK/game/server/tf/raid/tf_raid_logic.cpp"
  "$SDK/game/server/tf/serverbenchmark_tf.cpp"
  "$SDK/game/server/tf/te_tfblood.cpp"
  "$SDK/game/server/tf/tf_ammo_pack.cpp"
  "$SDK/game/server/tf/tf_autobalance.cpp"
  "$SDK/game/server/tf/tf_bot_temp.cpp"
  "$SDK/game/server/tf/tf_client.cpp"
  "$SDK/game/server/tf/tf_entity_spawner.cpp"
  "$SDK/game/server/tf/tf_eventlog.cpp"
  "$SDK/game/server/tf/tf_extra_map_entity.cpp"
  "$SDK/game/server/tf/tf_filters.cpp"
  "$SDK/game/server/tf/tf_fx.cpp"
  "$SDK/game/server/tf/tf_gameinterface.cpp"
  "$SDK/game/server/tf/tf_gamestats.cpp"
  "$SDK/game/server/tf/tf_gc_server.cpp"
  "$SDK/game/server/tf/tf_glow.cpp"
  "$SDK/game/server/tf/tf_hltvdirector.cpp"
  "$SDK/game/server/tf/tf_logic_on_holiday.cpp"
  "$SDK/game/server/tf/tf_obj.cpp"
  "$SDK/game/server/tf/tf_obj_catapult.cpp"
  "$SDK/game/server/tf/tf_obj_dispenser.cpp"
  "$SDK/game/server/tf/tf_obj_sapper.cpp"
  "$SDK/game/server/tf/tf_obj_sentrygun.cpp"
  "$SDK/game/server/tf/tf_obj_spy_trap.cpp"
  "$SDK/game/server/tf/tf_obj_teleporter.cpp"
  "$SDK/game/server/tf/tf_objective_resource.cpp"
  "$SDK/game/server/tf/tf_passtime_ball.cpp"
  "$SDK/game/server/tf/tf_passtime_logic.cpp"
  "$SDK/game/server/tf/tf_player.cpp"
  "$SDK/game/server/tf/tf_player_resource.cpp"
  "$SDK/game/server/tf/tf_playerclass.cpp"
  "$SDK/game/server/tf/tf_playermove.cpp"
  "$SDK/game/server/tf/tf_powerup.cpp"
  "$SDK/game/server/tf/tf_projectile_arrow.cpp"
  "$SDK/game/server/tf/tf_projectile_energy_ball.cpp"
  "$SDK/game/server/tf/tf_projectile_flare.cpp"
  "$SDK/game/server/tf/tf_projectile_rocket.cpp"
  "$SDK/game/server/tf/tf_props.cpp"
  "$SDK/game/server/tf/tf_pushentity.cpp"
  "$SDK/game/server/tf/tf_tactical_mission.cpp"
  "$SDK/game/server/tf/tf_taunt_prop.cpp"
  "$SDK/game/server/tf/tf_team.cpp"
  "$SDK/game/server/tf/tf_triggers.cpp"
  "$SDK/game/server/tf/tf_turret.cpp"
  "$SDK/game/server/tf/tf_voteissues.cpp"
  "$SDK/game/server/tf/tf_wartracker.cpp"
  "$SDK/game/server/tf/tf_weapon_builder.cpp"
  "$SDK/game/server/tf/trigger_catapult.cpp"
  "$SDK/game/server/tf/trigger_passtime_ball.cpp"
  "$SDK/game/server/tf/workshop/maps_workshop.cpp"
  "$SDK/game/server/trigger_area_capture.cpp"
  "$SDK/game/server/vguiscreen.cpp"
  "$SDK/game/server/vote_controller.cpp"
  "$SDK/game/server/vscript_server.cpp"
  "$SDK/game/server/waterbullet.cpp"
  "$SDK/game/server/wcedit.cpp"
  "$SDK/game/server/weight_button.cpp"
  "$SDK/game/shared/Multiplayer/multiplayer_animstate.cpp"
  "$SDK/game/shared/SceneCache.cpp"
  "$SDK/game/shared/SpriteTrail.cpp"
  "$SDK/game/shared/achievement_saverestore.cpp"
  "$SDK/game/shared/achievementmgr.cpp"
  "$SDK/game/shared/achievements_hlx.cpp"
  "$SDK/game/shared/base_playeranimstate.cpp"
  "$SDK/game/shared/baseachievement.cpp"
  "$SDK/game/shared/basegrenade_shared.cpp"
  "$SDK/game/shared/baseprojectile.cpp"
  "$SDK/game/shared/death_pose.cpp"
  "$SDK/game/shared/econ/attribute_manager.cpp"
  "$SDK/game/shared/econ/econ_claimcode.cpp"
  "$SDK/game/shared/econ/econ_dynamic_recipe.cpp"
  "$SDK/game/shared/econ/econ_entity.cpp"
  "$SDK/game/shared/econ/econ_entity_creation.cpp"
  "$SDK/game/shared/econ/econ_holidays.cpp"
  "$SDK/game/shared/econ/econ_item.cpp"
  "$SDK/game/shared/econ/econ_item_constants.cpp"
  "$SDK/game/shared/econ/econ_item_interface.cpp"
  "$SDK/game/shared/econ/econ_item_inventory.cpp"
  "$SDK/game/shared/econ/econ_item_preset.cpp"
  "$SDK/game/shared/econ/econ_item_schema.cpp"
  "$SDK/game/shared/econ/econ_item_schema_sdk.cpp"
  "$SDK/game/shared/econ/econ_item_system.cpp"
  "$SDK/game/shared/econ/econ_item_tools.cpp"
  "$SDK/game/shared/econ/econ_item_view.cpp"
  "$SDK/game/shared/econ/econ_paintkit.cpp"
  "$SDK/game/shared/econ/econ_quests.cpp"
  "$SDK/game/shared/econ/econ_wearable.cpp"
  "$SDK/game/shared/econ/item_selection_criteria.cpp"
  "$SDK/game/shared/econ/localization_provider.cpp"
  "$SDK/game/shared/effect_dispatch_data.cpp"
  "$SDK/game/shared/ehandle.cpp"
  "$SDK/game/shared/env_detail_controller.cpp"
  "$SDK/game/shared/env_wind_shared.cpp"
  "$SDK/game/shared/func_ladder.cpp"
  "$SDK/game/shared/gamemovement.cpp"
  "$SDK/game/shared/gc_clientsystem.cpp"
  "$SDK/game/shared/gc_replicated_convars.cpp"
  "$SDK/game/shared/hintmessage.cpp"
  "$SDK/game/shared/hintsystem.cpp"
  "$SDK/game/shared/hl2/survival_gamerules.cpp"
  "$SDK/game/shared/lobby.cpp"
  "$SDK/game/shared/obstacle_pushaway.cpp"
  "$SDK/game/shared/particle_parse.cpp"
  "$SDK/game/shared/playerclass_info_parse.cpp"
  "$SDK/game/shared/point_bonusmaps_accessor.cpp"
  "$SDK/game/shared/point_posecontroller.cpp"
  "$SDK/game/shared/replay_gamestats_shared.cpp"
  "$SDK/game/shared/rope_helpers.cpp"
  "$SDK/game/shared/sequence_Transitioner.cpp"
  "$SDK/game/shared/sheetsimulator.cpp"
  "$SDK/game/shared/singleplay_gamerules.cpp"
  "$SDK/game/shared/steamworks_gamestats_sdk.cpp"
  "$SDK/game/shared/teamplay_round_timer.cpp"
  "$SDK/game/shared/teamplayroundbased_gamerules.cpp"
  "$SDK/game/shared/test_ehandle.cpp"
  "$SDK/game/shared/tf/achievements_tf.cpp"
  "$SDK/game/shared/tf/achievements_tf_demoman.cpp"
  "$SDK/game/shared/tf/achievements_tf_engineer.cpp"
  "$SDK/game/shared/tf/achievements_tf_halloween.cpp"
  "$SDK/game/shared/tf/achievements_tf_heavy.cpp"
  "$SDK/game/shared/tf/achievements_tf_maps.cpp"
  "$SDK/game/shared/tf/achievements_tf_medic.cpp"
  "$SDK/game/shared/tf/achievements_tf_mvm.cpp"
  "$SDK/game/shared/tf/achievements_tf_pyro.cpp"
  "$SDK/game/shared/tf/achievements_tf_scout.cpp"
  "$SDK/game/shared/tf/achievements_tf_sniper.cpp"
  "$SDK/game/shared/tf/achievements_tf_soldier.cpp"
  "$SDK/game/shared/tf/achievements_tf_spy.cpp"
  "$SDK/game/shared/tf/baseobject_shared.cpp"
  "$SDK/game/shared/tf/entity_bonuspack.cpp"
  "$SDK/game/shared/tf/entity_capture_flag.cpp"
  "$SDK/game/shared/tf/entity_halloween_pickup.cpp"
  "$SDK/game/shared/tf/halloween/eyeball_boss/teleport_vortex.cpp"
  "$SDK/game/shared/tf/halloween/tf_weapon_spellbook.cpp"
  "$SDK/game/shared/tf/passtime_convars.cpp"
  "$SDK/game/shared/tf/passtime_game_events.cpp"
  "$SDK/game/shared/tf/quest_objective_manager.cpp"
  "$SDK/game/shared/tf/quest_objective_trackers.cpp"
  "$SDK/game/shared/tf/shared_object_tracker.cpp"
  "$SDK/game/shared/tf/tf_classdata.cpp"
  "$SDK/game/shared/tf/tf_condition.cpp"
  "$SDK/game/shared/tf/tf_dropped_weapon.cpp"
  "$SDK/game/shared/tf/tf_duckleaderboard.cpp"
  "$SDK/game/shared/tf/tf_flame.cpp"
  "$SDK/game/shared/tf/tf_fx_shared.cpp"
  "$SDK/game/shared/tf/tf_gamemovement.cpp"
  "$SDK/game/shared/tf/tf_gamerules.cpp"
  "$SDK/game/shared/tf/tf_gamestats_shared.cpp"
  "$SDK/game/shared/tf/tf_gc_shared.cpp"
  "$SDK/game/shared/tf/tf_gcmessages.cpp"
  "$SDK/game/shared/tf/tf_generic_bomb.cpp"
  "$SDK/game/shared/tf/tf_halloween_souls_pickup.cpp"
  "$SDK/game/shared/tf/tf_item.cpp"
  "$SDK/game/shared/tf/tf_item_constants.cpp"
  "$SDK/game/shared/tf/tf_item_inventory.cpp"
  "$SDK/game/shared/tf/tf_item_powerup_bottle.cpp"
  "$SDK/game/shared/tf/tf_item_schema.cpp"
  "$SDK/game/shared/tf/tf_item_system.cpp"
  "$SDK/game/shared/tf/tf_item_wearable.cpp"
  "$SDK/game/shared/tf/tf_ladder_data.cpp"
  "$SDK/game/shared/tf/tf_lobby_server.cpp"
  "$SDK/game/shared/tf/tf_lobby_shared.cpp"
  "$SDK/game/shared/tf/tf_logic_halloween_2014.cpp"
  "$SDK/game/shared/tf/tf_logic_player_destruction.cpp"
  "$SDK/game/shared/tf/tf_logic_robot_destruction.cpp"
  "$SDK/game/shared/tf/tf_mann_vs_machine_stats.cpp"
  "$SDK/game/shared/tf/tf_mapinfo.cpp"
  "$SDK/game/shared/tf/tf_match_description.cpp"
  "$SDK/game/shared/tf/tf_match_description_casual.cpp"
  "$SDK/game/shared/tf/tf_match_description_comp.cpp"
  "$SDK/game/shared/tf/tf_match_description_mvm.cpp"
  "$SDK/game/shared/tf/tf_match_description_shared.cpp"
  "$SDK/game/shared/tf/tf_matchmaking_shared.cpp"
  "$SDK/game/shared/tf/tf_obj_baseupgrade_shared.cpp"
  "$SDK/game/shared/tf/tf_party.cpp"
  "$SDK/game/shared/tf/tf_player_shared.cpp"
  "$SDK/game/shared/tf/tf_playeranimstate.cpp"
  "$SDK/game/shared/tf/tf_playerclass_info_parse.cpp"
  "$SDK/game/shared/tf/tf_playerclass_shared.cpp"
  "$SDK/game/shared/tf/tf_point_manager.cpp"
  "$SDK/game/shared/tf/tf_progression.cpp"
  "$SDK/game/shared/tf/tf_progression_description.cpp"
  "$SDK/game/shared/tf/tf_progression_description_casual.cpp"
  "$SDK/game/shared/tf/tf_progression_description_comp.cpp"
  "$SDK/game/shared/tf/tf_projectile_base.cpp"
  "$SDK/game/shared/tf/tf_projectile_dragons_fury.cpp"
  "$SDK/game/shared/tf/tf_projectile_energy_ring.cpp"
  "$SDK/game/shared/tf/tf_projectile_nail.cpp"
  "$SDK/game/shared/tf/tf_proto_script_obj_def.cpp"
  "$SDK/game/shared/tf/tf_pumpkin_bomb.cpp"
  "$SDK/game/shared/tf/tf_quest_map.cpp"
  "$SDK/game/shared/tf/tf_quest_map_node.cpp"
  "$SDK/game/shared/tf/tf_quest_map_utils.cpp"
  "$SDK/game/shared/tf/tf_quest_restriction.cpp"
  "$SDK/game/shared/tf/tf_revive.cpp"
  "$SDK/game/shared/tf/tf_robot_destruction_robot.cpp"
  "$SDK/game/shared/tf/tf_shareddefs.cpp"
  "$SDK/game/shared/tf/tf_target_dummy.cpp"
  "$SDK/game/shared/tf/tf_upgrades_shared.cpp"
  "$SDK/game/shared/tf/tf_usermessages.cpp"
  "$SDK/game/shared/tf/tf_viewmodel.cpp"
  "$SDK/game/shared/tf/tf_wardata.cpp"
  "$SDK/game/shared/tf/tf_weapon_bat.cpp"
  "$SDK/game/shared/tf/tf_weapon_bonesaw.cpp"
  "$SDK/game/shared/tf/tf_weapon_bottle.cpp"
  "$SDK/game/shared/tf/tf_weapon_buff_item.cpp"
  "$SDK/game/shared/tf/tf_weapon_club.cpp"
  "$SDK/game/shared/tf/tf_weapon_compound_bow.cpp"
  "$SDK/game/shared/tf/tf_weapon_dragons_fury.cpp"
  "$SDK/game/shared/tf/tf_weapon_fireaxe.cpp"
  "$SDK/game/shared/tf/tf_weapon_fists.cpp"
  "$SDK/game/shared/tf/tf_weapon_flamethrower.cpp"
  "$SDK/game/shared/tf/tf_weapon_flaregun.cpp"
  "$SDK/game/shared/tf/tf_weapon_grapplinghook.cpp"
  "$SDK/game/shared/tf/tf_weapon_grenade_pipebomb.cpp"
  "$SDK/game/shared/tf/tf_weapon_grenadelauncher.cpp"
  "$SDK/game/shared/tf/tf_weapon_invis.cpp"
  "$SDK/game/shared/tf/tf_weapon_jar.cpp"
  "$SDK/game/shared/tf/tf_weapon_jar_gas.cpp"
  "$SDK/game/shared/tf/tf_weapon_knife.cpp"
  "$SDK/game/shared/tf/tf_weapon_laser_pointer.cpp"
  "$SDK/game/shared/tf/tf_weapon_lunchbox.cpp"
  "$SDK/game/shared/tf/tf_weapon_mechanical_arm.cpp"
  "$SDK/game/shared/tf/tf_weapon_medigun.cpp"
  "$SDK/game/shared/tf/tf_weapon_minigun.cpp"
  "$SDK/game/shared/tf/tf_weapon_parachute.cpp"
  "$SDK/game/shared/tf/tf_weapon_parse.cpp"
  "$SDK/game/shared/tf/tf_weapon_particle_cannon.cpp"
  "$SDK/game/shared/tf/tf_weapon_passtime_gun.cpp"
  "$SDK/game/shared/tf/tf_weapon_pda.cpp"
  "$SDK/game/shared/tf/tf_weapon_pipebomblauncher.cpp"
  "$SDK/game/shared/tf/tf_weapon_pistol.cpp"
  "$SDK/game/shared/tf/tf_weapon_raygun.cpp"
  "$SDK/game/shared/tf/tf_weapon_revolver.cpp"
  "$SDK/game/shared/tf/tf_weapon_rocketlauncher.cpp"
  "$SDK/game/shared/tf/tf_weapon_rocketpack.cpp"
  "$SDK/game/shared/tf/tf_weapon_shotgun.cpp"
  "$SDK/game/shared/tf/tf_weapon_shovel.cpp"
  "$SDK/game/shared/tf/tf_weapon_slap.cpp"
  "$SDK/game/shared/tf/tf_weapon_smg.cpp"
  "$SDK/game/shared/tf/tf_weapon_sniperrifle.cpp"
  "$SDK/game/shared/tf/tf_weapon_sword.cpp"
  "$SDK/game/shared/tf/tf_weapon_syringegun.cpp"
  "$SDK/game/shared/tf/tf_weapon_throwable.cpp"
  "$SDK/game/shared/tf/tf_weapon_wrench.cpp"
  "$SDK/game/shared/tf/tf_weaponbase.cpp"
  "$SDK/game/shared/tf/tf_weaponbase_grenadeproj.cpp"
  "$SDK/game/shared/tf/tf_weaponbase_gun.cpp"
  "$SDK/game/shared/tf/tf_weaponbase_melee.cpp"
  "$SDK/game/shared/tf/tf_weaponbase_merasmus_grenade.cpp"
  "$SDK/game/shared/tf/tf_weaponbase_rocket.cpp"
  "$SDK/game/shared/tf/tf_wearable_campaign_item.cpp"
  "$SDK/game/shared/tf/tf_wearable_levelable_item.cpp"
  "$SDK/game/shared/tf/tf_wearable_weapons.cpp"
  "$SDK/game/shared/tf/tf_wheel_of_doom.cpp"
  "$SDK/game/shared/tf/trigger_catapult_shared.cpp"
  "$SDK/game/shared/vscript_shared.cpp"
  "$SDK/game/shared/weapon_ifmbase.cpp"
  "$SDK/game/shared/weapon_ifmbasecamera.cpp"
  "$SDK/game/shared/weapon_ifmsteadycam.cpp"
  "$SDK/game/shared/workshop/ugc_utils.cpp"
  "$SDK/public/ScratchPadUtils.cpp"
  "$SDK/public/SoundParametersInternal.cpp"
  "$SDK/public/editor_sendcommand.cpp"
  "$SDK/public/filesystem_helpers.cpp"
  "$SDK/public/haptics/haptic_msgs.cpp"
  "$SDK/public/keyframe/keyframe.cpp"
  "$SDK/public/networkvar.cpp"
  "$SDK/public/rope_physics.cpp"
  "$SDK/public/scratchpad3d.cpp"
  "$SDK/public/server_class.cpp"
  "$SDK/public/simple_physics.cpp"
  "$SDK/public/tier0/memoverride.cpp"
  "$SDK/tier1/splitstring.cpp"
  "$SDK/tier1/memstack.cpp"
  "$SDK/tier1/checksum_sha1.cpp"
  "$SDK/tier1/NetAdr.cpp"
  "$SDK/tier1/ilocalize.cpp"
  "$SDK/gcsdk/steamextra/rtime.cpp"
  "$SDK/gcsdk/steamextra/tier1/murmurhash3.cpp"
  "$SDK/gcsdk/steamextra/tier1/hashglobals.cpp"
  "$HERE/shim/libstub.cpp"
)

EXPORTS='_sim_collision_load,_sim_collision_stats,_sim_disp_load,_sim_disp_count,_sim_trace_hull,_sim_trace_result,_sim_point_contents,_sim_alloc,_sim_free'

mkdir -p "$OUT"
mkdir -p "$OUT/generated"
mkdir -p "$OUT/proto"

for proto in "${PROTO_SOURCES[@]}" "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/descriptor.proto"; do
  if ! "$PROTOC" --proto_path="$SDK/thirdparty/protobuf-2.6.1/src" --proto_path="$(dirname "$proto")" \
      --proto_path="$SDK/gcsdk" --proto_path="$SDK/game/shared" \
      --cpp_out="$OUT/proto" "$proto"; then
    echo "  FAIL  protoc $(basename "$proto")"
    exit 1
  fi
done

PROTOBUF_SOURCES=(
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/stubs/atomicops_internals_x86_gcc.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/stubs/common.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/stubs/once.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/stubs/stringprintf.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/stubs/structurally_valid.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/stubs/strutil.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/stubs/substitute.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/io/coded_stream.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/io/printer.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/io/strtod.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/io/tokenizer.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/io/zero_copy_stream.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/io/zero_copy_stream_impl.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/io/zero_copy_stream_impl_lite.cc"
  "$OUT/proto/google/protobuf/descriptor.pb.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/descriptor.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/descriptor_database.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/dynamic_message.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/extension_set.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/extension_set_heavy.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/generated_message_reflection.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/generated_message_util.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/message.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/message_lite.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/reflection_ops.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/repeated_field.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/service.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/text_format.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/unknown_field_set.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/wire_format.cc"
  "$SDK/thirdparty/protobuf-2.6.1/src/google/protobuf/wire_format_lite.cc"
  "$OUT/proto/steammessages.pb.cc"
  "$OUT/proto/base_gcmessages.pb.cc"
  "$OUT/proto/econ_gcmessages.pb.cc"
  "$OUT/proto/tf_gcmessages.pb.cc"
  "$OUT/proto/tf_proto_def_messages.pb.cc"
)

python "$HERE/tools/genclass.py" --tu "$OUT/genclass_tu.cpp"
if ! em++ -E "$OUT/genclass_tu.cpp" -o "$OUT/genclass_tu.i" \
    "${INCLUDES[@]}" "${DEFINES[@]}" "${FLAGS[@]}" 2>"$OUT/genclass_tu.log"; then
  echo "  FAIL  interface preprocess"
  tail -20 "$OUT/genclass_tu.log"
  exit 1
fi
python "$HERE/tools/genclass.py" "$OUT/genclass_tu.i" "$HERE/shim/generated" >/dev/null

for nut in "$SDK"/game/server/*.nut; do
  base="$(basename "${nut%.nut}")"
  out="$OUT/generated/${base}_nut.h"
  if [ ! -f "$out" ] || [ "$nut" -nt "$out" ]; then
    python "$HERE/tools/nut2h.py" "$nut" "$out" "$base"
  fi
done

fail=0

echo "nav subsystem"
for src in "${NAV_SOURCES[@]}"; do
  name="$(basename "${src%.cpp}")"
  if em++ -c "$src" -o "$OUT/$name.o" "${INCLUDES[@]}" "${DEFINES[@]}" "${FLAGS[@]}" 2>"$OUT/$name.log"; then
    echo "  ok    $name"
  else
    echo "  FAIL  $name"
    grep -E "error:" "$OUT/$name.log" | head -5
    fail=1
  fi
done

echo "collision module"
if em++ "${COLLISION_SOURCES[@]}" -o "$OUT/simcollision.wasm" \
    "${INCLUDES[@]}" "${DEFINES[@]}" "${FLAGS[@]}" \
    --no-entry -sSTANDALONE_WASM -sEXPORTED_FUNCTIONS="$EXPORTS" \
    -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=64MB 2>"$OUT/simcollision.log"; then
  echo "  ok    simcollision.wasm ($(stat -c%s "$OUT/simcollision.wasm") bytes)"
else
  echo "  FAIL  simcollision.wasm"
  grep -E "error:|undefined symbol" "$OUT/simcollision.log" | head -8
  fail=1
fi

echo "entity module"
mkdir -p "$OUT/ents"

RSP="$OUT/entflags.rsp"
: > "$RSP"
for arg in "${INCLUDES[@]}" "${DEFINES[@]}" "${FLAGS[@]}"; do
  case "$arg" in
    -I*) printf '"-I%s"\n' "$(cygpath -m "${arg#-I}" 2>/dev/null || echo "${arg#-I}")" >> "$RSP" ;;
    *)   printf '"%s"\n' "$arg" >> "$RSP" ;;
  esac
done

cat > "$OUT/cc.sh" <<'CCEOF'
#!/usr/bin/env bash
name="${1%%|*}"
src="${1#*|}"
if em++ -c "$src" -o "$OUT/ents/$name.o" "@$RSP" 2>"$OUT/ents/$name.log"; then
  echo "  ok    $name"
else
  echo "  FAIL  $name"
  grep -E "error:" "$OUT/ents/$name.log" | head -5
  exit 1
fi
CCEOF
chmod +x "$OUT/cc.sh"
export OUT RSP

worklist="$OUT/ents.work"
: > "$worklist"
entobjs=()
for src in "${PROTOBUF_SOURCES[@]}" "${ENT_SOURCES[@]}"; do
  case "$src" in
    *.cc) name="pb_$(basename "$src" .cc)" ;;
    *)    name="$(basename "$src" .cpp)" ;;
  esac
  obj="$OUT/ents/$name.o"
  entobjs+=("$obj")
  if [ -f "$obj" ] && [ "$obj" -nt "$src" ] && [ "$obj" -nt "$HERE/build.sh" ]; then continue; fi
  printf '%s|%s\n' "$name" "$src" >> "$worklist"
done

if [ -s "$worklist" ]; then
  echo "  $(grep -c '' "$worklist") translation units, $JOBS at a time"
  if ! xargs -a "$worklist" -d '\n' -P "$JOBS" -I{} "$OUT/cc.sh" {}; then
    fail=1
  fi
fi

LINKRSP="$OUT/entlink.rsp"
: > "$LINKRSP"
for obj in "${entobjs[@]}"; do
  printf '"%s"\n' "$(cygpath -m "$obj" 2>/dev/null || echo "$obj")" >> "$LINKRSP"
done

if em++ "@$LINKRSP" -o "$OUT/ents.wasm" \
    --no-entry -sSTANDALONE_WASM -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=64MB \
    -sERROR_ON_UNDEFINED_SYMBOLS=1 -Wl,--error-limit=0 2>"$OUT/entslink.log"; then
  echo "  ok    ents.wasm ($(stat -c%s "$OUT/ents.wasm") bytes)"
  if [ -n "${NAMED:-}" ]; then
    em++ "@$LINKRSP" -o "$OUT/ents_named.wasm" \
      --no-entry -sSTANDALONE_WASM -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=64MB \
      --profiling-funcs -sERROR_ON_UNDEFINED_SYMBOLS=1 2>"$OUT/entslink_named.log" \
      && echo "  ok    ents_named.wasm ($(stat -c%s "$OUT/ents_named.wasm") bytes)"
  fi
else
  echo "  link pending"
  grep -oE "(undefined|duplicate) symbol: .*" "$OUT/entslink.log" | sort -u | head -30
fi

exit $fail
